sudo: required
dist: trusty

language: cpp

cache: ccache

matrix:
 include:
   - dist: precise
     compiler: gcc
     env: LIBARCHIVE_OFF=FALSE

   - compiler: gcc
     env: LIBARCHIVE_OFF=FALSE

   - compiler: gcc
     env: LIBARCHIVE_OFF=TRUE

   - compiler: clang
     env: LIBARCHIVE_OFF=FALSE

   - compiler: gcc
     env: LIBARCHIVE_OFF=FALSE
          DEPLOY_BUILD=TRUE
   - os: osx
     osx_image: xcode6.4
     compiler: gcc
     env: LIBARCHIVE_OFF=TRUE
     
before_install:
 - wget https://github.com/orex/supercell/raw/deploy/deploy.sh && chmod +x deploy.sh
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; sudo apt-get install -qq libboost-program-options-dev libboost-regex-dev libboost-filesystem-dev libboost-random-dev libboost-system-dev libeigen3-dev libarchive-dev liblzma-dev libbz2-dev zlib1g-dev; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install eigen; fi
 - if [[ ${DEPLOY_BUILD} == TRUE && "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq texlive-extra-utils python texlive-extra-utils texlive-latex-extra python-pygments texlive-science texlive-humanities texlive-pstricks texlive-fonts-recommended; fi
 - if [[ ${DEPLOY_BUILD} == TRUE && "$TRAVIS_OS_NAME" == "osx" ]]; then echo "OSX deploy build"; fi
 - export c_path=${PWD}

install:
 - cd ~ 
 - git clone https://github.com/openbabel/openbabel.git
 - cd openbabel && mkdir build && cd build
 - cmake ../ -DCMAKE_BUILD_TYPE=Release `[[ ${DEPLOY_BUILD} == TRUE ]] && echo "-DMINIMAL_BUILD=OFF -DBUILD_GUI=OFF -DBUILD_SHARED=OFF -DGLIBC_24_COMPATIBLE=ON -DWITH_INCHI=OFF -DENABLE_VERSIONED_FORMATS=OFF -DENABLE_TESTS=OFF"`
 - make && sudo make install
 - cd ~

before_script:
 - cd ${c_path}
 - mkdir build
 - cd build
 - cmake ../ -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_DISABLE_FIND_PACKAGE_LibArchive=${LIBARCHIVE_OFF} `[[ ${DEPLOY_BUILD} == TRUE ]] && echo "-DCMAKE_BUILD_TYPE=Release -DGLIBC_24_COMPATIBLE=ON -DLINK_STATIC_LIBS=ON" || echo "-DCMAKE_BUILD_TYPE=Debug"`
 - wget https://github.com/gpoore/minted/raw/master/source/minted.sty -O doc/tutorial/minted.sty
 - wget https://raw.githubusercontent.com/gpoore/fvextra/master/fvextra/fvextra.sty -O doc/tutorial/fvextra.sty

script:
 - make `[[ ${DEPLOY_BUILD} == TRUE ]] && echo "supercell doc_man doc_pdf doc_html tutorial_pdf" || echo "supercell"`
 - ./src/sc_cli/supercell -d -i ../data/examples/Ca2Al2SiO7/Ca2Al2SiO7.cif

deploy:
  provider: script
  script: ${c_path}/deploy.sh
  skip_cleanup: true
  on:
    branch: master
    condition: $DEPLOY_BUILD = TRUE
