language: cpp

compiler:
 - gcc
 - clang

env:
 - LIBARCHIVE_OFF=TRUE
 - LIBARCHIVE_OFF=FALSE

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libboost-program-options-dev libboost-regex-dev libboost-filesystem-dev libboost-random-dev libboost-system-dev openbabel texlive-extra-utils python libeigen3-dev libarchive-dev
 - export c_path=${PWD}

install:
 - cd ~ 
 - git clone https://github.com/openbabel/openbabel.git
 - cd openbabel && mkdir build && cd build
 - cmake ../ -DCMAKE_BUILD_TYPE=Release && make && sudo make install
 - cd ~

before_script:
 - cd ${c_path}
 - mkdir build
 - cd build
 - cmake ../ -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_DISABLE_FIND_PACKAGE_LibArchive=${LIBARCHIVE_OFF}

script:
 - make supercell
 - ./src/sc_cli/supercell -d -i ../data/examples/Ca2Al2SiO7/Ca2Al2SiO7.cif
